import designMode  from './designMode';
import cookies from './cookies';
import url from './url';
import fullscreen from './fullscreen';
import event from './event';
import crypto from './crypto';
import a from './a';
import o from './o';
import f from './f';
import geo from './geolocation';
import storage from './storage';

export const DesignMode: designMode;
export const Cookies: cookies;
export const Url: url;
export const Fullscreen: fullscreen;
export const Event: event;
export const Crypto: crypto;
export const A: a;
export const O: o;
export const F: f;
export const Geo: geo;
export const Storage: storage