import cookies from './cookies';
import url from './url';
import fullscreen from './fullscreen';
import event from './event';
import crypto from './crypto';
export * as DesignMode from './designMode';
export const Cookies: cookies;
export const Url: url;
export const Fullscreen: fullscreen;
export const Event: event;
export const Crypto: crypto;